"""Read-only RF-CEM R4 observation and engineering-constraint layer."""

from .artifacts import (
    MANIFEST_FILE,
    R4Bundle,
    R4InstanceArtifacts,
    R4SourceSet,
    R4_BUNDLE_PREFIX,
    R4_BUNDLE_SCHEMA_VERSION,
    R4_MANIFEST_SCHEMA_VERSION,
    REGISTRY_FILE,
    load_r4_bundle,
    write_r4_bundle,
)
from .common import ConstraintContractError, ObservationContractError, SUPPORTED_UNITS
from .constraints import (
    CONSTRAINT_EVALUATION_SCHEMA_VERSION,
    CONSTRAINT_EVALUATOR_VERSION,
    ENGINEERING_CONSTRAINT_SCHEMA_VERSION,
    ConstraintEvaluation,
    ConstraintFinding,
    EngineeringConstraint,
    build_demonstration_constraints,
    evaluate_constraint,
    evaluate_constraints,
    load_constraint_evaluation,
    load_engineering_constraint,
)
from .contracts import (
    EXACT_GEOMETRY_REFERENCE_SCHEMA_VERSION,
    OBSERVATION_BUNDLE_SCHEMA_VERSION,
    SCALAR_DESCRIPTOR_REGISTRY_SCHEMA_VERSION,
    SEMANTIC_SHAPE_OBSERVATION_SCHEMA_VERSION,
    ContractIdentityRef,
    ExactGeometryReference,
    GeometryArtifactIdentity,
    LandmarkObservation,
    MonotonicInterval,
    ObservationBundle,
    RegionShapeObservation,
    ScalarDescriptorDefinition,
    ScalarDescriptorRegistry,
    ScalarDescriptorValue,
    SemanticShapeObservation,
    ShapeSample,
    load_exact_geometry_reference,
    load_observation_bundle,
    load_scalar_descriptor_registry,
    load_semantic_shape_observation,
)
from .descriptors import (
    DESCRIPTOR_ALGORITHM_VERSION,
    REQUIRED_DESCRIPTOR_IDS,
    build_default_descriptor_registry,
    build_observation_bundle,
    extract_scalar_descriptors,
)
from .observer import (
    DEFAULT_SAMPLES_PER_REGION,
    SHAPE_OBSERVER_VERSION,
    RegionCurveInput,
    build_exact_geometry_reference,
    landmark_observations_from_compiled,
    observe_compiled_geometry,
    observe_region_curves,
    region_curves_from_compiled,
)


ARCHITECTURE_LAYER = "observation"

__all__ = [
    "ARCHITECTURE_LAYER",
    "CONSTRAINT_EVALUATION_SCHEMA_VERSION",
    "CONSTRAINT_EVALUATOR_VERSION",
    "ConstraintContractError",
    "ConstraintEvaluation",
    "ConstraintFinding",
    "ContractIdentityRef",
    "DEFAULT_SAMPLES_PER_REGION",
    "DESCRIPTOR_ALGORITHM_VERSION",
    "ENGINEERING_CONSTRAINT_SCHEMA_VERSION",
    "EXACT_GEOMETRY_REFERENCE_SCHEMA_VERSION",
    "EngineeringConstraint",
    "ExactGeometryReference",
    "GeometryArtifactIdentity",
    "LandmarkObservation",
    "MANIFEST_FILE",
    "MonotonicInterval",
    "OBSERVATION_BUNDLE_SCHEMA_VERSION",
    "ObservationBundle",
    "ObservationContractError",
    "R4Bundle",
    "R4InstanceArtifacts",
    "R4SourceSet",
    "R4_BUNDLE_PREFIX",
    "R4_BUNDLE_SCHEMA_VERSION",
    "R4_MANIFEST_SCHEMA_VERSION",
    "REGISTRY_FILE",
    "REQUIRED_DESCRIPTOR_IDS",
    "RegionCurveInput",
    "RegionShapeObservation",
    "SCALAR_DESCRIPTOR_REGISTRY_SCHEMA_VERSION",
    "SEMANTIC_SHAPE_OBSERVATION_SCHEMA_VERSION",
    "SHAPE_OBSERVER_VERSION",
    "SUPPORTED_UNITS",
    "ScalarDescriptorDefinition",
    "ScalarDescriptorRegistry",
    "ScalarDescriptorValue",
    "SemanticShapeObservation",
    "ShapeSample",
    "build_default_descriptor_registry",
    "build_demonstration_constraints",
    "build_exact_geometry_reference",
    "build_observation_bundle",
    "evaluate_constraint",
    "evaluate_constraints",
    "extract_scalar_descriptors",
    "landmark_observations_from_compiled",
    "load_constraint_evaluation",
    "load_engineering_constraint",
    "load_exact_geometry_reference",
    "load_observation_bundle",
    "load_r4_bundle",
    "load_scalar_descriptor_registry",
    "load_semantic_shape_observation",
    "observe_compiled_geometry",
    "observe_region_curves",
    "region_curves_from_compiled",
    "write_r4_bundle",
]
