"""Deterministic no-CST Semantic Acquisition probes."""

from .a0_coverage import (
    A0_ALGORITHM_VERSION,
    A0_BUNDLE_PREFIX,
    A0_BUNDLE_SCHEMA_VERSION,
    A0_MANIFEST_SCHEMA_VERSION,
    A0_REPORT_SCHEMA_VERSION,
    A0Bundle,
    A0SourceSet,
    CoverageEvaluation,
    CoverageMatch,
    PrimaryAvailabilityAudit,
    TruthData,
    TruthJunction,
    audit_lerec_availability,
    boundary_trace_from_compile_record,
    evaluate_coverage,
    load_truth_junctions,
    write_a0_bundle,
)
from .boundary_signals import (
    BOUNDARY_SIGNAL_ALGORITHM_VERSION,
    DEFAULT_SAMPLE_COUNTS,
    BoundaryJoin,
    BoundaryPoint,
    BoundarySegment,
    BoundarySignalError,
    BoundaryTrace,
    CandidateExtraction,
    ContinuitySignalDiagnostic,
    LandmarkCandidate,
    ScaleCandidate,
    SignalParameters,
    extract_landmark_candidates,
    resample_by_arc_length,
    signed_curvature,
)


ARCHITECTURE_LAYER = "semantic_acquisition"

__all__ = [
    "A0_ALGORITHM_VERSION",
    "A0_BUNDLE_PREFIX",
    "A0_BUNDLE_SCHEMA_VERSION",
    "A0_MANIFEST_SCHEMA_VERSION",
    "A0_REPORT_SCHEMA_VERSION",
    "ARCHITECTURE_LAYER",
    "BOUNDARY_SIGNAL_ALGORITHM_VERSION",
    "DEFAULT_SAMPLE_COUNTS",
    "A0Bundle",
    "A0SourceSet",
    "BoundaryJoin",
    "BoundaryPoint",
    "BoundarySegment",
    "BoundarySignalError",
    "BoundaryTrace",
    "CandidateExtraction",
    "ContinuitySignalDiagnostic",
    "CoverageEvaluation",
    "CoverageMatch",
    "LandmarkCandidate",
    "PrimaryAvailabilityAudit",
    "ScaleCandidate",
    "SignalParameters",
    "TruthData",
    "TruthJunction",
    "audit_lerec_availability",
    "boundary_trace_from_compile_record",
    "evaluate_coverage",
    "extract_landmark_candidates",
    "load_truth_junctions",
    "resample_by_arc_length",
    "signed_curvature",
    "write_a0_bundle",
]
