"""Translate the 500 MHz baseline UDSG into CST v0 action/script artifacts."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path, PureWindowsPath
from typing import Literal

from .history_templates import CstHistoryBlock, CstHistoryTemplates


FilenameMode = Literal["star-basename", "absolute"]


@dataclass(frozen=True)
class TranslationArtifacts:
    """Generated CSTTranslator v0 artifacts."""

    actions: list[dict]
    mapping_table: dict
    script: str
    report: dict


def emit_step_import_block(
    step_file: Path,
    *,
    filename_mode: FilenameMode = "star-basename",
    scale_to_unit: str = "0",
    import_id: str = "1",
    import_curves: str = "True",
    import_attributes: str = "True",
    import_curve_attributes: str = "True",
) -> str:
    """Emit the observed CST VBA STEP import block."""
    filename = _step_filename_argument(step_file, filename_mode)
    return "\n".join(
        [
            "With STEP",
            "     .Reset",
            f"     .ScaleToUnit \"{scale_to_unit}\"",
            f"     .FileName \"{filename}\"",
            f"     .Id \"{import_id}\"",
            "     .Version \"11.0\"",
            "     .ImportToActiveCoordinateSystem \"True\"",
            f"     .Curves \"{import_curves}\"",
            f"     .ImportAttributes \"{import_attributes}\"",
            f"     .ImportCurveAttributes \"{import_curve_attributes}\"",
            "     .UpdateMaterialPropertiesFromMaterialLibrary \"False\"",
            "     .Read",
            "End With",
        ]
    )


def emit_assign_imported_vacuum_material_block(
    *,
    imported_solid_name: str = "default:Open CASCADE STEP translator 7.7 1",
    material_name: str = "Vacuum",
) -> str:
    """Assign the imported RF vacuum body to CST's Vacuum material.

    Evidence source: live-CST ModelHistory generated by changing the imported
    STEP solid material to Vacuum in CST 2026.  Length/frequency units are not
    changed by this action.
    """
    return f'Solid.ChangeMaterial "{imported_solid_name}", "{material_name}"'


def emit_copper_background_material_block() -> str:
    """Emit the verified CST background-material block for a copper cavity wall.

    Evidence source: ``D:\\ModelData\\bare\\Model\\3D\\ModelHistory.json``.
    The material uses mm/GHz/s units for the lossy-metal branch and
    conductivity 5.8e7 S/m, matching the historical Copper (annealed) block.
    The imported RF vacuum solid is assigned separately.
    """
    return "\n".join(
        [
            "With Background ",
            "     .ResetBackground ",
            "     .XminSpace \"0.0\" ",
            "     .XmaxSpace \"0.0\" ",
            "     .YminSpace \"0.0\" ",
            "     .YmaxSpace \"0.0\" ",
            "     .ZminSpace \"0.0\" ",
            "     .ZmaxSpace \"0.0\" ",
            "     .ApplyInAllDirections \"False\" ",
            "End With ",
            "",
            "With Material ",
            "     .Reset ",
            "     .Rho \"8930.0\"",
            "     .ThermalType \"Normal\"",
            "     .ThermalConductivity \"401.0\"",
            "     .SpecificHeat \"390\", \"J/K/kg\"",
            "     .DynamicViscosity \"0\"",
            "     .UseEmissivity \"True\"",
            "     .Emissivity \"0\"",
            "     .MetabolicRate \"0\"",
            "     .VoxelConvection \"0\"",
            "     .BloodFlow \"0\"",
            "     .Absorptance \"0\"",
            "     .MechanicsType \"Isotropic\"",
            "     .YoungsModulus \"120\"",
            "     .PoissonsRatio \"0.33\"",
            "     .ThermalExpansionRate \"17\"",
            "     .IntrinsicCarrierDensity \"0\"",
            "     .FrqType \"all\"",
            "     .Type \"Lossy metal\"",
            "     .MaterialUnit \"Frequency\", \"GHz\"",
            "     .MaterialUnit \"Geometry\", \"mm\"",
            "     .MaterialUnit \"Time\", \"s\"",
            "     .Mu \"1.0\"",
            "     .Sigma \"5.8e+007\"",
            "     .LossyMetalSIRoughness \"0.0\"",
            "     .ReferenceCoordSystem \"Global\"",
            "     .CoordSystemType \"Cartesian\"",
            "     .NLAnisotropy \"False\"",
            "     .NLAStackingFactor \"1\"",
            "     .NLADirectionX \"1\"",
            "     .NLADirectionY \"0\"",
            "     .NLADirectionZ \"0\"",
            "     .FrqType \"static\"",
            "     .Type \"Normal\"",
            "     .MaterialUnit \"Frequency\", \"Hz\"",
            "     .MaterialUnit \"Geometry\", \"mm\"",
            "     .MaterialUnit \"Time\", \"s\"",
            "     .Epsilon \"1\"",
            "     .Mu \"1.0\"",
            "     .Sigma \"5.8e+007\"",
            "     .TanD \"0.0\"",
            "     .TanDFreq \"0.0\"",
            "     .TanDGiven \"False\"",
            "     .TanDModel \"ConstTanD\"",
            "     .SetConstTanDStrategyEps \"AutomaticOrder\"",
            "     .ConstTanDModelOrderEps \"3\"",
            "     .DjordjevicSarkarUpperFreqEps \"0\"",
            "     .SetElParametricConductivity \"False\"",
            "     .ReferenceCoordSystem \"Global\"",
            "     .CoordSystemType \"Cartesian\"",
            "     .SigmaM \"0\"",
            "     .TanDM \"0.0\"",
            "     .TanDMFreq \"0.0\"",
            "     .TanDMGiven \"False\"",
            "     .TanDMModel \"ConstTanD\"",
            "     .SetConstTanDStrategyMu \"AutomaticOrder\"",
            "     .ConstTanDModelOrderMu \"3\"",
            "     .DjordjevicSarkarUpperFreqMu \"0\"",
            "     .SetMagParametricConductivity \"False\"",
            "     .DispModelEps  \"None\"",
            "     .DispModelMu \"None\"",
            "     .DispersiveFittingSchemeEps \"Nth Order\"",
            "     .MaximalOrderNthModelFitEps \"10\"",
            "     .ErrorLimitNthModelFitEps \"0.1\"",
            "     .UseOnlyDataInSimFreqRangeNthModelEps \"False\"",
            "     .DispersiveFittingSchemeMu \"Nth Order\"",
            "     .MaximalOrderNthModelFitMu \"10\"",
            "     .ErrorLimitNthModelFitMu \"0.1\"",
            "     .UseOnlyDataInSimFreqRangeNthModelMu \"False\"",
            "     .UseGeneralDispersionEps \"False\"",
            "     .UseGeneralDispersionMu \"False\"",
            "     .NLAnisotropy \"False\"",
            "     .NLAStackingFactor \"1\"",
            "     .NLADirectionX \"1\"",
            "     .NLADirectionY \"0\"",
            "     .NLADirectionZ \"0\"",
            "     .Colour \"1\", \"1\", \"0\" ",
            "     .Wireframe \"False\" ",
            "     .Reflection \"False\" ",
            "     .Allowoutline \"True\" ",
            "     .Transparentoutline \"False\" ",
            "     .Transparency \"0\" ",
            "     .ChangeBackgroundMaterial",
            "End With",
        ]
    )


def translate_baseline(
    udsg: dict,
    templates: CstHistoryTemplates,
    step_file: Path,
    *,
    filename_mode: FilenameMode = "star-basename",
    require_postprocessing: bool = False,
) -> TranslationArtifacts:
    """Compile UDSG and history templates into deterministic CST artifacts."""
    import_block = emit_step_import_block(step_file, filename_mode=filename_mode)
    actions = _build_actions(import_block, templates)
    mapping_table = _build_mapping_table(udsg, step_file)
    report = _build_report(udsg, templates, step_file, filename_mode, require_postprocessing)
    script = _emit_vba_script(actions, report)
    return TranslationArtifacts(actions=actions, mapping_table=mapping_table, script=script, report=report)


def _build_actions(import_block: str, templates: CstHistoryTemplates) -> list[dict]:
    blocks = [
        ("set_units", "define units", templates.units_block),
        ("set_background_material", "define copper background material", emit_copper_background_material_block()),
        ("import_step", "import step geometry", import_block),
        ("assign_imported_vacuum_material", "assign imported RF vacuum material", emit_assign_imported_vacuum_material_block()),
        ("set_boundary", "define boundaries", templates.boundary_block),
        ("set_frequency_range", "define frequency range", templates.frequency_range_block),
    ]
    blocks.extend(
        (f"set_eigenmode_solver_{index:02d}", f"define eigenmode solver block {index}", block)
        for index, block in enumerate(templates.solver_blocks, start=1)
    )
    actions = [
        {
            "action_id": action_id,
            "action_type": action_id,
            "caption": caption,
            "backend": "cst_vba",
            "vba": block,
        }
        for action_id, caption, block in blocks
    ]
    actions.extend(_postprocessing_actions(templates))
    return actions


def _build_mapping_table(udsg: dict, step_file: Path) -> dict:
    features = [
        feature
        for feature in udsg.get("features", [])
        if feature.get("status") in {"confirmed", "modified"}
    ]
    feature_to_geometry = {
        str(feature.get("id")): list(feature.get("geometry_refs", []))
        for feature in sorted(features, key=lambda item: str(item.get("id")))
    }
    geometry_to_features: dict[str, list[str]] = {}
    for feature_id, refs in feature_to_geometry.items():
        for ref in refs:
            geometry_to_features.setdefault(str(ref), []).append(feature_id)
    overlaps = {
        ref: sorted(ids)
        for ref, ids in sorted(geometry_to_features.items())
        if len(ids) > 1
    }
    feature_to_cst_action = {}
    for feature in features:
        feature_id = str(feature.get("id"))
        feature_type = str(feature.get("type"))
        if feature_type == "RFVacuumVolume":
            feature_to_cst_action[feature_id] = ["ImportSTEP", "AssignImportedSolidMaterial:Vacuum"]
        elif feature_type == "ConductingWall":
            feature_to_cst_action[feature_id] = ["SetGlobalBackgroundMaterial:Copper(annealed)", "UseGlobalBoundary:electric"]
        elif feature.get("default_boundary_role") == "open_or_electric_by_recipe":
            feature_to_cst_action[feature_id] = ["UseRecipeBoundary:electric"]
        else:
            feature_to_cst_action[feature_id] = ["SemanticMappingOnly"]

    return {
        "schema_version": "cst_mapping_table.v0",
        "input_udsg_schema": udsg.get("schema_version"),
        "source_step": str(step_file),
        "feature_to_geometry": feature_to_geometry,
        "feature_to_cst_action": dict(sorted(feature_to_cst_action.items())),
        "geometry_overlaps": overlaps,
        "unresolved": [],
        "warnings": [
            "v0 emits global boundary settings only; face-level boundary assignments are not generated.",
            "STEP import does not guarantee post-import CST component/solid names.",
        ],
    }


def _build_report(
    udsg: dict,
    templates: CstHistoryTemplates,
    step_file: Path,
    filename_mode: FilenameMode,
    require_postprocessing: bool,
) -> dict:
    warnings = list(udsg.get("validation", {}).get("warnings", []))
    blocking_errors: list[str] = []
    if filename_mode == "star-basename":
        warnings.append(
            "STEP import uses observed CST history filename form '*basename.stp'; live-CST should verify path resolution."
        )
    if not _has_verified_postprocessing(templates):
        message = (
            "No verified CST postprocessing/result-template history blocks found for Freq/RQ/Q; "
            "translator did not emit guessed postprocessing VBA."
        )
        if require_postprocessing:
            blocking_errors.append(message)
        else:
            warnings.append(message)
    if templates.macro_fallback_candidates:
        warnings.append(
            "Macro fallback candidates were discovered but are not emitted by default; validate RunScript/RunMacro on a disposable CST project first."
        )
    return {
        "schema_version": "translator_report.v0",
        "status": "blocked" if blocking_errors else "ok",
        "blocking_errors": blocking_errors,
        "warnings": warnings,
        "source_step_absolute": str(step_file.resolve()),
        "step_filename_mode": filename_mode,
        "history_template_source": templates.source,
        "eigenmode_summary": templates.eigenmode_summary,
        "postprocessing_summary": _postprocessing_summary(templates),
        "symmetry": udsg.get("geometry", {}).get("symmetry", {}),
        "notes": [
            "Generated script is no-CST validated and intended for follow-up live-CST smoke testing.",
            "review_session.json differences are audit-only; reviewed_feature_labels.yaml drove UDSG features.",
            "Global RF wall policy sets the background material to historical Copper (annealed) before geometry import.",
            "Imported RF vacuum volume is assigned to CST Vacuum material before solver setup.",
        ],
    }


def _postprocessing_actions(templates: CstHistoryTemplates) -> list[dict]:
    actions: list[dict] = []
    for block in (
        list(templates.monitor_blocks)
        + list(templates.postprocessing_blocks)
        + list(templates.result_template_blocks)
        + list(templates.result_export_blocks)
    ):
        actions.append(_action_from_history_block(block))
    return actions


def _action_from_history_block(block: CstHistoryBlock) -> dict:
    return {
        "action_id": block.action_id,
        "action_type": _postprocessing_action_type(block),
        "caption": block.caption,
        "backend": "cst_vba",
        "vba": block.vba,
        "source_index": block.source_index,
        "classifier": {
            "category": block.category,
            "subcategory": block.subcategory,
            "confidence": block.confidence,
            "source_kind": block.source_kind,
        },
    }


def _postprocessing_action_type(block: CstHistoryBlock) -> str:
    if block.category == "monitors" and block.subcategory != "template_based_postprocessing":
        return "set_field_monitor"
    if block.subcategory == "template_based_postprocessing":
        return "run_postprocessing_macro"
    if block.subcategory == "result_template":
        return "set_result_template"
    return "export_result"


def _has_verified_postprocessing(templates: CstHistoryTemplates) -> bool:
    return bool(templates.postprocessing_blocks or templates.result_template_blocks or templates.result_export_blocks)


def _postprocessing_summary(templates: CstHistoryTemplates) -> dict:
    return {
        "monitor_blocks": len(templates.monitor_blocks),
        "postprocessing_blocks": len(templates.postprocessing_blocks),
        "result_template_blocks": len(templates.result_template_blocks),
        "result_export_blocks": len(templates.result_export_blocks),
        "macro_fallback_candidates": len(templates.macro_fallback_candidates),
        "verified": _has_verified_postprocessing(templates),
    }


def _emit_vba_script(actions: list[dict], report: dict) -> str:
    lines = [
        "' RF-CEM CSTTranslator v0 generated script",
        f"' Report: {json.dumps(report, sort_keys=True)}",
        "Sub Main()",
    ]
    for action in actions:
        lines.append(f"    ' Action: {action['action_id']}")
        lines.extend(f"    {line}" if line.strip() else "" for line in str(action["vba"]).splitlines())
        lines.append("")
    lines.append("End Sub")
    return "\n".join(lines) + "\n"


def _step_filename_argument(step_file: Path, filename_mode: FilenameMode) -> str:
    raw_path = str(step_file)
    windows_path = PureWindowsPath(raw_path)
    if filename_mode == "star-basename":
        # CST filenames are Windows paths even when no-CST translation runs on Linux CI.
        return f"*{windows_path.name}"
    if filename_mode == "absolute":
        if windows_path.is_absolute():
            return str(windows_path)
        return str(step_file.resolve())
    raise ValueError(f"Unsupported STEP filename mode: {filename_mode}")
